# Generated by Django 4.2.5 on 2023-09-27 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_usuario_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('geolocalization', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('profile', models.CharField(choices=[('farmer', 'Fazendeiro'), ('agronomist', 'Agrônomo'), ('cooperative', 'Cooperativa')], max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
        migrations.AddField(
            model_name='farm',
            name='AgronomistId',
            field=models.ForeignKey(limit_choices_to={'agronomist'}, on_delete=django.db.models.deletion.CASCADE, related_name='Agronomists', to='app1.users'),
        ),
        migrations.AddField(
            model_name='farm',
            name='cooperativeID',
            field=models.ForeignKey(limit_choices_to={'cooperative'}, on_delete=django.db.models.deletion.CASCADE, related_name='cooperatives', to='app1.users'),
        ),
        migrations.AddField(
            model_name='farm',
            name='farmerId',
            field=models.ForeignKey(limit_choices_to={'farmer'}, on_delete=django.db.models.deletion.CASCADE, related_name='farms', to='app1.users'),
        ),
    ]
