# Generated by Django 4.2.5 on 2023-09-28 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_farm_users_delete_usuario_farm_agronomistid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Harvest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localization', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='References',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('internalRef', models.FloatField(max_length=4)),
                ('externalRef', models.FloatField(max_length=4)),
            ],
        ),
        migrations.AlterField(
            model_name='farm',
            name='AgronomistId',
            field=models.ForeignKey(limit_choices_to={'profile': 'agronomist'}, on_delete=django.db.models.deletion.CASCADE, related_name='Agronomists', to='app1.users'),
        ),
        migrations.AlterField(
            model_name='farm',
            name='cooperativeID',
            field=models.ForeignKey(limit_choices_to={'profile': 'cooperative'}, on_delete=django.db.models.deletion.CASCADE, related_name='cooperatives', to='app1.users'),
        ),
        migrations.AlterField(
            model_name='farm',
            name='farmerId',
            field=models.ForeignKey(limit_choices_to={'profile': 'farmer'}, on_delete=django.db.models.deletion.CASCADE, related_name='farms', to='app1.users'),
        ),
        migrations.CreateModel(
            name='Tillage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startdate', models.DateField(auto_now=True)),
                ('active', models.BooleanField(default=False)),
                ('enddate', models.DateField()),
                ('health', models.CharField(max_length=100)),
                ('usedseed', models.CharField(choices=[('Thompson_Seedless', 'Uva Thompson Seedless'), ('Red_Globe', 'Uva Red Globe'), ('Flame_Seedless', 'Uva Flame Seedless'), ('Concord', 'Uva Concord'), ('Muscat', 'Uva Muscat'), ('Cabernet_Sauvignon', 'Uva Cabernet Sauvignon'), ('Chardonnay', 'Uva Chardonnay'), ('Merlot', 'Uva Merlot'), ('Pinot_Noir', 'Uva Pinot Noir'), ('Zinfandel', 'Uva Zinfandel')], max_length=60)),
                ('harvestId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tillages', to='app1.harvest')),
            ],
        ),
        migrations.CreateModel(
            name='Pictures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('notes', models.CharField(max_length=400)),
                ('file', models.CharField(max_length=100)),
                ('tillagedId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picsoftillage', to='app1.tillage')),
            ],
        ),
        migrations.CreateModel(
            name='Humidity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('humidity', models.FloatField(max_length=4)),
                ('tillageId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tillages', to='app1.tillage')),
            ],
        ),
        migrations.AddField(
            model_name='harvest',
            name='farmId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harvests', to='app1.farm'),
        ),
    ]
