# Generated by Django 4.2.5 on 2023-11-28 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_harvest_references_alter_farm_agronomistid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farm',
            name='AgronomistId',
        ),
        migrations.RemoveField(
            model_name='farm',
            name='cooperativeID',
        ),
        migrations.RemoveField(
            model_name='farm',
            name='farmerId',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
