# Generated by Django 4.2.5 on 2023-11-28 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_remove_farm_agronomistid_remove_farm_cooperativeid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='harvest',
            old_name='farmId',
            new_name='farm',
        ),
    ]
