# Generated by Django 4.2.5 on 2023-11-29 01:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_remove_pictures_file_pictures_filelink_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='humidity',
            name='tillageId',
        ),
        migrations.AddField(
            model_name='humidity',
            name='tillage',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, related_name='humidities', to='app1.tillage'),
            preserve_default=False,
        ),
    ]
